# src/constants.py

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 450
SCREEN_TITLE = "Geometry Dash: Bad copy"

SPRITE_SCALING_PLAYER = 0.5
SPRITE_SCALING_WALL = 1.0
SPRITE_SCALING_SPIKE = 0.6

GRAVITY = 0.9
JUMP_SPEED = 14
PLAYER_SPEED_EASY = 5
PLAYER_SPEED_MEDIUM = 8

STATE_MENU = 0
STATE_GAME = 1
STATE_GAME_OVER = 2

STATUS_NONE = 0
STATUS_WIN = 1
STATUS_LOSS = 2